### PR TITLE
Status white space fix

### PR DESCRIPTION
**Pull request by fe-lix-werner**
Removed unnecessary whitespace above status

### CODE REVIEW

**Comment by yorickvanzweeden** [comment]
When I checkout this branch, and then run ./install.sh. I only get the status notification


I'm guessing, as I have an update pending, that this case is not handled. Otherwise, be sure to try to install it from scratch yourself!

**Comment by fe-lix-werner** [comment]
> When I checkout this branch, and then run ./install.sh. I only get the status notification
> 
> 
> I'm guessing, as I have an update pending, that this case is not handled. Otherwise, be sure to try to install it from scratch yourself!

Sorry I'm new to github but can try checking out the status-white-space-fix branch? Or is it private? Bc thats where i added the fix.

**Comment by yorickvanzweeden** [comment]
@fe-lix-werner  No problem ;) I did check out your forked repository. The result is that I only see two options.

#### status-white-space-fix branch:

---
#### master:
imageedit_1_4280304637

---
I think this is due to this message:
Screenshot from 2020-04-20 10-54-03


As there is no branch in your if statement for this status. But I could be wrong here. Therefore I encourage you to try it yourself one more time. (Checkout, then run ./install)

**Comment by fe-lix-werner** [comment]
This is what i get when checking it out. Maybe i haven't made the problem clear. The problem is hitting status and having annoying whitespace above the the status message

This is what it looks like when i checkout the status-whitespace-fix branch
image

**Comment by fe-lix-werner** [comment]
This is what it looks like if i install your master:
image

**Comment by yorickvanzweeden** [comment]
Interesting to see the differences. I would like to note the following:

Please be aware that `status.raw_status` returns the raw string that is slightly modified. As nordvpn updates their application every X weeks, it is somewhat useless to keep up with them. So we display the status as is.

In your case, this results in whitespace. Could you run `nordvpn status` in your application and check if the whitespace also occurs there? I encourage you to look at `nordvpn.py:51`. This is function `update(self, raw_status)`


Also note that you are splitting the raw string on the occurence of 'C' or 'D'. For me, the raw string is
```
A new version of NordVPN is available! Please update the application.
Status: Disconnected
```
I hope you understand how this results in faulty output for me.

**Review by yorickvanzweeden — CHANGES_REQUESTED** [review]
Please review why you get faulty output in the first place by reviewing `nordvpn.py:51 function update`. Then decide how you will create a generalized case from this. You could strip from the left on whitespace and dashes?

**Review by fe-lix-werner — COMMENTED** [review]
Didn't figure out what causes the whitespaces and hyphens but made a specific method which strips everything from the status until it finds a alphabetic character

**Comment by yorickvanzweeden** [comment]
@fe-lix-werner Sorry for not responding; Codacy fails for code style. This is shown in the PR overview.
The link for this is: https://app.codacy.com/manual/yorickvanzweeden/Ubuntu-NordVPN-Indicator/pullRequest?prid=5385271

Additionally, I receive the following error when running your fork:

```
Traceback (most recent call last):
  File "/opt/ubuntu-nordvpn-indicator/nordvpn_indicator.py", line 323, in <module>
    main()
  File "/opt/ubuntu-nordvpn-indicator/nordvpn_indicator.py", line 320, in main
    Indicator(NordVPN())
  File "/opt/ubuntu-nordvpn-indicator/nordvpn_indicator.py", line 47, in __init__
    self.status_check_loop()
  File "/opt/ubuntu-nordvpn-indicator/nordvpn_indicator.py", line 54, in status_check_loop
    self.update()
  File "/opt/ubuntu-nordvpn-indicator/nordvpn_indicator.py", line 63, in update
    self.status_label.set_label(status.get_label_status())
  File "/opt/ubuntu-nordvpn-indicator/nordvpn.py", line 104, in get_label_status
    return re.findall('[a-zA-Z](?s:.)*',self.raw_status)[0]
  File "/usr/lib/python2.7/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
  File "/usr/lib/python2.7/re.py", line 251, in _compile
    raise error, v # invalid expression
sre_constants.error: unknown extension
```

Last remark, you can shorten the regex part `[a-zA-Z]` to `[A-z]`. See [ascii table](http://www.asciitable.com/)

**Review by fe-lix-werner — COMMENTED** [review]
Hope everything is gtg now :+1:

**Comment by yorickvanzweeden** [comment]
Hey @fe-lix-werner, I think you are misunderstanding the concept of pull requests a bit; which is totally okay ;)

When you fork a repository and then try to merge back, all changes to the repository are added to the pull request (PR). This can be viewed in the section 'Changes'. So when you changed your README.md, it is also in the pull request. Additionally, pull requests are automatically updated when you update your branch.

Then there are some events that are triggered after each pull request update. These are part of Continuous Integration. For this repository, I setup Codacy and gitguardian. Codacy checks the code style for Python and enforces that it's up to standards. The report can be shown if you click 'Details' next to Codacy (on the PR overview). The other one is Git Guardian. This is a service from Github that sends me an email when credentials are accidentally committed to the repository. If one of these checks fails, I won't merge it.

A third point, is to make the changes small and isolated. If there are a lot of changes, the chance of a bug slipping through is higher, and reverting one small thing requires reverting all of the changes. You started out really good with a small change, but the last two commits affect the entire repository.

I could understand if these practices seem tedious, but I can guarantee you adhering to them helps to maintain workable software. Here is a list of good resources:
- [Git best practices](https://deepsource.io/blog/git-best-practices/)
- [Pull request best practices](https://www.atlassian.com/blog/git/written-unwritten-guide-pull-requests)
- [Some notes on code quality (tools like Codacy)](https://www.perforce.com/blog/sca/what-code-quality-and-how-improve-it)

**Comment by fe-lix-werner** [comment]
Hi @yorickvanzweeden ,
thank you so much for patience and your will to explain. I've only used gitlab before and fucked up merging. I just reverted the merge and now i actually think everything should be fine :)

**Review by yorickvanzweeden — APPROVED** [review]
Nice work!

**Pull request merged**
